#!/bin/bash
# 📊 RÉSUMÉ NETTOYAGE ET CONFIGURATION V2 - 2025-12-08

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║  🚀 FRENCH LLM V2 TRAINING - OPTIMISÉ RTX 5080 + R7 9700X                 ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📊 NETTOYAGE EFFECTUÉ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ SUPPRIMÉ (60GB libérés):"
echo "   ├─ data_clean/french_pd_books/                    (36GB)"
echo "   ├─ data_clean/corpus_10g.bin                      (11GB)"
echo "   ├─ data_clean/corpus_test_*.bin                   (600MB)"
echo "   ├─ data_clean/french_large/                       (1.7GB)"
echo "   ├─ data_clean/conversations_all/                  (23MB)"
echo "   ├─ data_clean/conversations_extra/                (31MB)"
echo "   ├─ data_clean/conversations_hf/                   (VARIOUS)"
echo "   ├─ data_clean/conversations_massive/              (843MB)"
echo "   ├─ data_clean/fineweb*/                           (VARIOUS)"
echo "   └─ trained_models/runs/OLD_RUNS/                  (plusieurs GB)"
echo ""

echo "✅ CONSERVÉ (données essentielles):"
echo "   ├─ data_clean/v2_tokenized/                       (12GB) ⭐"
echo "   ├─ data_clean/conversations_mega_train.txt        (337MB)"
echo "   ├─ data_clean/conversations_mega_test.txt         (60MB)"
echo "   ├─ data_clean/conversations_mega_tokenized.pt     (1.5GB)"
echo "   ├─ trained_models/runs/checkpoint_step_17500.pt   (3GB)"
echo "   └─ trained_models/runs/checkpoint_step_100000.pt  (3GB)"
echo ""

echo "🖥️  MATÉRIEL DÉTECTÉ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "GPU:"
echo "   • Modèle: RTX 5080"
echo "   • VRAM: 16GB GDDR7"
echo "   • Architecture: Ada (sm_89)"
echo "   • Bandwidth: 576 GB/s"
echo "   • FP32 Performance: ~44.1 TFLOPS"
echo "   • Tensor Performance: ~353 TFLOPS (TF32)"
echo ""

echo "CPU:"
echo "   • Modèle: R7 9700X"
echo "   • Cores: 8 / Threads: 16"
echo "   • Base Freq: 4.5 GHz"
echo "   • Boost Freq: 5.5 GHz"
echo "   • TDP: 105W (OC)"
echo "   • Cache: 64MB L3"
echo ""

echo "RAM:"
echo "   • Capacité: 64GB"
echo "   • Type: DDR5"
echo "   • Bandwidth: ~88GB/s (theoretical)"
echo "   • Latency: ~45-50ns"
echo ""

echo "Storage:"
echo "   • Interface: NVMe PCIe 4.0"
echo "   • Theoretical Speed: ~7GB/s"
echo "   • Effective: 3-4GB/s (avec overhead)"
echo ""

echo "⚡ OPTIMISATIONS PYTORCH CONFIGURÉES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ CUDA Optimisations:"
echo "  ├─ CUDA_LAUNCH_BLOCKING=0         (Async execution)"
echo "  ├─ max_split_size_mb=512          (Memory fragmentation)"
echo "  ├─ expandable_segments=True       (Dynamic allocation)"
echo "  ├─ TORCH_BACKENDS_CUDNN_BENCHMARK (Kernel auto-tuning)"
echo "  └─ TF32 Precision                 (RTX 5080 native)"
echo ""

echo "✓ Mixed Precision (AMP):"
echo "  ├─ Forward: FP16                  (-50% mémoire)"
echo "  ├─ Backward: FP32                 (stabilité)"
echo "  └─ Loss scaling: Dynamique        (évite underflow)"
echo ""

echo "✓ Memory Optimisations:"
echo "  ├─ Gradient Checkpointing         (-30% mémoire)"
echo "  ├─ Pin Memory                     (+50% BW DDR5→GPU)"
echo "  ├─ Persistent Workers             (-CPU overhead)"
echo "  └─ Prefetch Factor: 2             (DDR5 optimisé)"
echo ""

echo "✓ Computation Optimisations:"
echo "  ├─ torch.compile (BETA)           (+30% vitesse)"
echo "  ├─ Flash Attention                (RTX 5080 compatible)"
echo "  ├─ CUDNN Convolution              (auto-optimized)"
echo "  └─ Stride tricks                  (memory coalescing)"
echo ""

echo "✓ CPU Optimisations:"
echo "  ├─ OMP_NUM_THREADS=8              (8 cores R7 9700X)"
echo "  ├─ OMP_DYNAMIC=FALSE              (static)"
echo "  ├─ MKL_NUM_THREADS=8              (Intel MKL if avail)"
echo "  └─ OPENBLAS_NUM_THREADS=8         (OpenBLAS support)"
echo ""

echo "📈 CONFIGURATION ENTRAÎNEMENT V2"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Modèle:"
echo "  • Vocab Size: 32,000 (nouveau tokenizer)"
echo "  • Hidden Size: 1024"
echo "  • Num Layers: 18"
echo "  • Attention Heads: 16"
echo "  • FFN Dim: 4096"
echo "  • Max Position: 4096"
echo "  • Total Params: ~260M"
echo ""

echo "Hyperparamètres:"
echo "  • Batch Size (per GPU): 16"
echo "  • Gradient Accumulation: 4"
echo "  • Effective Batch Size: 64"
echo "  • Learning Rate: 1e-4"
echo "  • Weight Decay: 0.01"
echo "  • Warmup Steps: 500"
echo "  • Max Training Steps: 200,000"
echo ""

echo "Checkpointing:"
echo "  • Save Frequency: Tous les 2,500 steps"
echo "  • Eval Frequency: Tous les 1,000 steps"
echo "  • Checkpoint Dir: trained_models/runs/french_v2_optimized_rtx5080/"
echo ""

echo "📊 PERFORMANCES ESTIMÉES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Throughput:"
echo "  • Samples/sec: 2-3 (batch=16)"
echo "  • Tokens/sec: ~32k-48k (4096 tokens/sample)"
echo "  • TFLOPS utilisé: ~100-120 (RTX 5080 peak: 353 TFLOPS)"
echo ""

echo "Memory:"
echo "  • Model: ~1GB"
echo "  • Activations: ~8GB (avec gradient checkpointing)"
echo "  • Optimizer: ~2GB (Adam)"
echo "  • Total: ~11-13GB / 16GB"
echo ""

echo "Timing:"
echo "  • Steps pour complétion: 200,000"
echo "  • Temps estimé: 24-30 heures"
echo "  • Checkpoints générés: 80"
echo ""

echo "🚀 LANCEMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Scripts créés:"
echo ""
echo "1️⃣  launch_v2.sh"
echo "   └─ Menu interactif pour démarrer l'entraînement"
echo "   └─ Options: Docker, Python, Dashboard, Vérification"
echo ""

echo "2️⃣  launch_optimized_v2_training.py"
echo "   └─ Configuration PyTorch optimisée"
echo "   └─ Vérification matériel et dépendances"
echo ""

echo "3️⃣  launch_v2_training_optimized.py"
echo "   └─ Launcher complet avec dashboard intégré"
echo "   └─ Génération de config automatique"
echo ""

echo "4️⃣  dashboard_pytorch.py"
echo "   └─ Interface web Flask en temps réel"
echo "   └─ Métriques: Loss, GPU mem, throughput, ETA"
echo "   └─ Port: 5000"
echo ""

echo "📍 DÉMARRAGE RAPIDE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option A: Menu interactif"
echo "  $ cd /home/vincent/code/repo/french-llm-from-scratch"
echo "  $ ./launch_v2.sh"
echo ""

echo "Option B: Docker (recommandé)"
echo "  $ docker-compose up -d"
echo "  $ docker-compose logs -f"
echo ""

echo "Option C: Python direct"
echo "  $ python3 launch_v2_training_optimized.py"
echo ""

echo "Option D: Dashboard seul"
echo "  $ python3 dashboard_pytorch.py"
echo "  $ open http://localhost:5000"
echo ""

echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Lire: README_V2_OPTIMIZED.md"
echo "  ✓ Optimisations détaillées"
echo "  ✓ Configuration avancée"
echo "  ✓ Troubleshooting"
echo "  ✓ Références techniques"
echo ""

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║  ✅ SYSTÈME PRÊT POUR L'ENTRAÎNEMENT                                       ║"
echo "║  🖥️  RTX 5080 + R7 9700X OC 105W optimisé                                 ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
