name: Docker Image CI

on:
  push:
    branches: [ "feat/french-llm-training" ]
  pull_request:
    branches: [ "feat/french-llm-training" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
